spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 274ca311-6cc1-48c5-b731-a711e374f0d4 # Nacos 命名空间 dev 的编号
